# Details about the site
site_name: "OS Sketch"
site_url: https://www.os-sketch.com
repo_url: https://github.com/OS-Sketch/www.os-sketch.com
copyright: Default

# Definition of the theme
theme:
  # Use the default theme and then customize it further
  name: material
  # Provide an overrides/ directory that contains a main.html file for customization
  custom_dir: overrides
  # Define the favicon that displays in the tab of the browser
  favicon: img/draw.svg
  # Define the logo for the repository for the top left-hand corner of the screen
  icon:
    logo: material/draw
    repo: fontawesome/brands/github
  # Define the fonts used on the site
  font:
    # The main font used in header, footer, and all body text
    text: IBM Plex Sans
    # The font used in all of the source code samples
    code: IBM Plex Mono
  # Create black menu bars at the top and bottom
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Enable features that are built-in to material for mkdocs
  features:
    # Allow a user to dismiss the announcement at the top of the page
    - announce.dismiss
    # Create a single-page application with faster loading evident
    # Note that this option prohibits the rendering of mathematics;
    # there was some evidence that this was not the case but now
    # it seems likely that using "instant" does break MathJax rendering;
    # Note that this may break the feedback mechanism
    - navigation.instant
    # Display tabs for main sections at top of page
    - navigation.tabs
    # Automatically expand the navigation for each section
    # Note that this might not be suitable for courses with many assignments
    # - navigation.expand
    # Offer a "Back to Top" button when person starts scrolling up on page
    - navigation.top
    # Make search suggestions when using project-wide search
    - search.suggest
    # Enable the sharing of searches with an icon in search box after start
    - search.share
    # Highlight search terms that match on the chosen page
    - search.highlight

# Extensions to markdown that provide the feature described above the extension itself
markdown_extensions:
  # Add HTML attributes and CSS classes to markdown elements
  - attr_list
  - md_in_html
  # Support the inclusion of snippets of HTML or Markdown from other files;
  # note that this extension also enables the chosen abbreviations approach
  - pymdownx.snippets:
  # Display and generate emojis using the standard notation (e.g., ":runner:")
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator:
        !!python/name:materialx.emoji.to_svg # Display mathematics using MathJax

  - pymdownx.arithmatex:
      generic: true
  # Display paragraph markers that exhibit as permalinks for section in a file
  - toc:
      permalink: true
  # Highlight source code
  - codehilite
  - markdown.extensions.codehilite:
      guess_lang: true
  # Admonitions in separate boxes
  - admonition
  # Make admonitions collapsible
  - pymdownx.details
  # Support extra social media icons in the footer
  - extra
  # Display keys with easier-to-read symbols
  - pymdownx.keys
  # Allow jump-to-and-jump back footnotes
  - footnotes
  # Display source code correctly with line numbers
  - pymdownx.superfences:
      custom_fences:
        - format:
            !!python/name:pymdownx.superfences.fence_div_format # Enable source code and admonitions to be tabbed

  - pymdownx.tabbed
  # Provide support for more intelligent emphasis and bolding
  - pymdownx.betterem:
      smart_enable: all
  # Support highlighting of text and super- and sub-scripts
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  # Support inserting special characters with greater ease
  - pymdownx.smartsymbols
  # Support the creation of customizable task lists
  - pymdownx.tasklist:
      custom_checkbox: true

# Install plugins
plugins:
  - search
  - git-committers:
      repository: OS-Sketch/www.os-sketch.com
      branch: master
      token: !ENV ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - tags:
      tags_file: tags.md
  # Minify the HTML source code to support faster downloads
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true

# Add icons and links to the footer
extra:
  social:
    # GitHub organization
    - icon: fontawesome/brands/github
      link: https://github.com/OS-Sketch/www.os-sketch.com
    # GitHub issue tracker
    - icon: fontawesome/brands/github-alt
      link: https://github.com/OS-Sketch/www.os-sketch.com/issues
    # GitHub discussions
    - icon: fontawesome/solid/comments
      link: https://github.com/OS-Sketch/discussions
    # Discord server invitation (open publicly)
    - icon: fontawesome/brands/discord
      link: https://discord.gg/9VfCdqffu6

# Load the stylesheet that overrides parts of the material for mkdocs theme
extra_css:
  - stylesheets/extra.css

# Load the JavaScript needed to support MathJax rendering inside of site
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree that defines the navigation structure
nav:
  - Introduction: index.md
  - Learning Objectives: operating-systems/learning-objectives.md
  - Learning Community: operating-systems/learning-community.md
  - Course Syllabus: operating-systems/syllabus.md
  - Course Schedule: operating-systems/schedule.md
  - Course Tools: operating-systems/course-tools.md
  - Topics List: tags.md
  - Sketches: operating-systems/sketches.md
