name: Report Bug on Web Site
description: File a bug report about the web site
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - gkapfham
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filling out this bug report about the OS-Sketch web site!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? Please note that your email address will be in a public GitHub issue.
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What happened when you were using the web site?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-what-happened
    attributes:
      label: What did you expect to happen?
      description: What did you expect to happen when you were using the web site?
      placeholder: Tell us what you would like to see!
      value: "I was expecting something different!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) exhibit the problem that you see?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: dropdown
    id: severity
    attributes:
      label: What is the severity of the bug in the web site?
      multiple: true
      options:
        - Not Severe
        - Mild Severity
        - Moderate Severity
        - Serious Severity
        - Showstopper Severity
  - type: textarea
    id: what-like
    attributes:
      label: What do you like about this web site?
      description: Explain what you have enjoyed so far about this site!
      placeholder: Tell us what you like!
      value: "I really like that OS-Sketch ..."
    validations:
      required: false
  - type: checkboxes
    id: terms-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/OS-Sketch/www.os-sketch.com/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
